spring:
  datasource:
    url: jdbc:postgresql://ep-summer-river-azzuc8iz.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_JhaFExI8czZ6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always # Executes schema.sql on startup if present

# Custom properties for external APIs
app:
  social:
    instagram:
      # Currently mocked, you can set real values using ENV variables e.g. INSTAGRAM_ACCESS_TOKEN
      access-token: "${INSTAGRAM_ACCESS_TOKEN:EAATW2J46zmABSJYwYibjiubpaLC52ZAKIp8rdv4RMUIPNZAuZAJDZCIIKWg7kghwMAtaNrGqtm1nGGlgyeaL1p95ZCdrFQT2v4yZCMfAzEdo8ENULdQUsoPJYRDmLN1ZCZAUlZApKBcMeDzWlCuCw3xZALfwSo1D2BbDuLrY9Bw1kVnoyEVK9ZABcZB1jdBHFszTzuzN8utpC2jveYjawE2A1R4MZB7KN9YHVwqWuL61fPn5gdZB5iRktspewKWOZCBZATSSwB53LBFk4mD2Mv4d5gZDZD}"
      account-id: "${INSTAGRAM_ACCOUNT_ID:17841440826407138}"
      api-version: "v20.0"
    youtube:
      api-key: "${YOUTUBE_API_KEY:mock_key}"
  ai:
    gemini:
      api-key: "${GEMINI_API_KEY:mock_key}"
